dashboard/urls.py
from django.conf.urls import url

from . import views


app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.dashboard_index, name='dashboard_index'),
]

goals/urls.py
from django.conf.urls import url

from . import views


app_name = 'goals'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.goal_detail, name='goal_detail'),
    url(r'^(?P<pk>[0-9]+)/complete$', views.goal_complete,
        name='goal_complete'),
    url(r'^add/$', views.add_goal, name='add_goal'),
    url(r'(?P<pk>[0-9]+)/delete$', views.delete_goal, name='delete_goal'),
]

hardclimbz/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^goals/', include('goals.urls')),
    url(r'^admin/', admin.site.urls),
]

goals/models.py
from django.db import models


class Goal(models.Model):
    """
    A single goal.
    """
    goal_title = models.CharField(max_length=200)
    goal_description = models.TextField()
    date_due = models.DateField()
    date_completed = models.DateField(blank=True, null=True)

    def completed(self):
        return self.date_completed is not None
    completed.boolean = True

    def completed_on_time(self):
        if not self.completed():
            return False
        return self.date_completed.date() <= self.date_due.date()
    completed_on_time.boolean = True

    def __str__(self):
        return self.goal_title


class Note(models.Model):
    """
    A note relating to a single :model:`.Goal`.
    """
    goal = models.ForeignKey('Goal', on_delete=models.CASCADE)
    note_text = models.TextField()
    date = models.DateTimeField(auto_now=True)

dashboard/views.py
from django.shortcuts import render

from goals.models import Goal


def dashboard_index(request):
    incomplete_goals_ids = [goal.id for goal in Goal.objects.all()
                            if not goal.completed()]
    incomplete_goals = Goal.objects.filter(id__in=incomplete_goals_ids) \
                                   .order_by('date_due')

    completed_goals_ids = [goal.id for goal in Goal.objects.all()
                           if goal.completed()]
    completed_goals = Goal.objects.filter(id__in=completed_goals_ids) \
                                  .order_by('-date_completed')

    goals_count = Goal.objects.all().count()
    completed_goals_count = len(completed_goals)

    context = {
        'goals_count': goals_count,
        'completed_goals_count': completed_goals_count,
        'goals_due_soon': incomplete_goals[:3],
        'recently_completed_goals': completed_goals[:3],
    }
    return render(request, 'dashboard/index.html', context)

goals/views.py
from datetime import date

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.dateparse import parse_date
from django.utils.translation import ugettext_lazy as _

from .models import Goal, Note


def goal_detail(request, pk):
    goal = get_object_or_404(Goal, pk=pk)

    if request.method == 'POST':
        note = request.POST['note-text']
        Note.objects.create(goal=goal, note_text=note)
        return HttpResponseRedirect(reverse('goals:goal_detail', args=(pk,)))

    return render(request, 'goals/goal_detail.html', {'goal': goal})


def goal_complete(request, pk):
    goal = get_object_or_404(Goal, pk=pk)
    date_completed = parse_date(request.POST['date-completed'])
    goal.date_completed = date_completed
    goal.save()

    return HttpResponseRedirect(reverse('goals:goal_detail', args=(pk,)))


def add_goal(request):
    goal_title = request.POST['goal-title']
    goal_description = request.POST['goal-description']
    date_due = request.POST['date-due']

    if parse_date(date_due) < date.today():
        messages.error(request,
                       _('Goals cannot have due dates earlier than today.'))
        return HttpResponseRedirect('/dashboard/')

    goal = Goal.objects.create(goal_title=goal_title,
                               goal_description=goal_description,
                               date_due=date_due)

    return HttpResponseRedirect(reverse('goals:goal_detail', args=(goal.id,)))


def delete_goal(request, pk):
    goal = get_object_or_404(Goal, pk=pk)
    messages.info(request, _('Deleted %s' % goal.goal_title))
    goal.delete()

    return HttpResponseRedirect('/dashboard/')

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% block content %}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 id="dashboard-header" class="title">Dashboard</h1>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <nav class="level is-mobile">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Goals</p>
          <p class="title">{{ goals_count }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Completed</p>
          <p class="title">{{ completed_goals_count }}</p>
        </div>
      </div>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <h1 class="title">Add New Goal</h1>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'error' %}
    <article class="message is-danger">
      {% elif message.tags == 'info' %}
      <article class="message is-info">
        {% endif %}
        <div class="message-body">
          {{ message }}
        </div>
      </article>
      {% endfor %}
      {% endif %}
      <form action="{% url 'goals:add_goal' %}" method="post">
        {% csrf_token %}
        <div class="control is-horizontal">
          <div class="control">
            <input id="goal_title" class="input" type="text" name="goal-title" placeholder="Goal Title" required />
          </div>
          <div class="control-label">
            <label class="label" for="date-due">Due Date:</label>
          </div>
          <div class="control">
            <input id="date_due" class="input" type="text" name="date-due" placeholder="YYYY-MM-DD" required />
          </div>
        </div>
        <div class="control">
          <textarea id="goal_description" class="textarea" name="goal-description" placeholder="What makes this goal so rad?" required></textarea>
        </div>
        <div class="control">
          <button id="add_goal" class="button is-primary" type="submit">Add Goal</button>
        </div>
      </form>
      <hr />
      <h1 class="title">Goals Due Soon</h1>
      <div class="columns">
        {% for goal in goals_due_soon %}
        <div class="column is-4">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                {{ goal.goal_title }}
              </p>
              <a class="card-header-icon" href="{% url 'goals:goal_detail' goal.id %}">
                <span class="icon">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </header>
            <div class="card-content">
              <nav class="level">
                <div class="level-item has-text-centered">
                  <div>
                    <p class="heading">Due In</p>
                    <p class="title">{{  goal.date_due|timeuntil }}</p>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <hr />
      <h1 class="title">Recently Completed Goals</h1>
      <div class="columns">
        {% for goal in recently_completed_goals %}
        <div class="column is-4">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                {{ goal.goal_title }}
              </p>
              <a class="card-header-icon" href="{% url 'goals:goal_detail' goal.id %}">
                <span class="icon">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </header>
            <div class="card-content">
              <nav class="level">
                <div class="level-item has-text-centered">
                  <div>
                    <p class="heading">Completed On</p>
                    <p class="title">{{  goal.date_completed }}</p>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  </div>
</section>
{% endblock %}

goals/templates/goals/goal_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="hero is-info">
  <div class="hero-body">
    <nav class="container">
      <div class="title">
        {{ goal.goal_title }}
      </div>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="tile is-ancestor">
      <div class="tile is-8">
        <div class="tile is-parent is-vertical">
          <div class="tile is-child notification is-primary">
            <p class="title">{{ goal.goal_title }}</p>
            <p class="subtitle">{{ goal.goal_description }}</p>
          </div>
        </div>
      </div>
      <div class="tile is-parent is-vertical">
        {% if goal.completed %}
        <div class="tile is-child notification is-success">
          <p class="title">Completed!</p>
          <p class="subtitle">Completed on {{  goal.date_completed|date:"l, N d, Y"  }}. Nice job!</p>
        </div>
        {% else %}
        <div class="tile is-child notification">
          <p class="title">Complete this goal</p>
          <p class="subtitle">Due on {{ goal.date_due|date:"l, N d, Y" }}</p>
          <form action="{% url 'goals:goal_complete' goal.id %}" method="post">
            {% csrf_token %}
            <p class="control">
              <label for="date-completed" class="label">Date completed:</label>
            </p>
            <p class="control has-addons">
              <input type="text" name="date-completed" class="input" placeholder="YYYY-MM-DD">
              <input class="button is-primary" type="submit" value="Complete!" />
            </p>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="tile ancestor is-pulled-right is-8">
      <div class="tile is-child notification is-danger">
        <p class="title">Hello, World!</p>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <h2 class="title">Notes</h2>
    {% for note in goal.note_set.all %}
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          {{ note.date|date:"l, N d, Y P" }}
        </p>
      </header>
      <div class="card-content">
        <p>{{ note.note_text }}</p>
      </div>
    </div>
    <br />
    {% endfor %}
    <form action="{% url 'goals:goal_detail' goal.id %}" method="post">
      {% csrf_token %}
      <p class="control">
        <textarea name="note-text" class="textarea" placeholder="Write a new note here..." required></textarea>
      </p>
      <p class="control">
        <input class="button control" type="submit" value="Add Note" />
      </p>
    </form>
    <hr />
    <h2 class="title">Edit Goal</h2>
    <a class="button is-danger" href="{% url 'goals:delete_goal' goal.id %}">Delete goal</a>
  </div>
</section>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HardClimbz</title>
    <link rel="stylesheet" href="{% static "styles.css" %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="nav has-shadow">
      <div class="container">
        <div class="nav-left">
          <a class="nav-item">
            <i class="fa fa-area-chart"></i>
          </a>
          <a class="nav-item is-tab is-hidden-mobile" href="{% url 'dashboard:dashboard_index' %}">Dashboard</a>
        </div>
        <div class="nav-right">
          <a class="nav-item">
            Log out
          </a>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <a href="https://gitlab.com/apsummers/hardclimbz">
              <i class="fa fa-gitlab"></i>
            </a>
          </p>
        </div>
      </div>
    </footer>
  </body>
</html>